import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

console.log(`NEXT_PUBLIC_TEST_VALUE: ${process.env.NEXT_PUBLIC_TEST_VALUE}`);
console.log(`TEST_INT: ${process.env.TEST_INT}`);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
