name: NextJS Test App CI

on:
  push:
    branches: [main]

env:
  NEXT_PUBLIC_TEST_VALUE: value-from-gh-actions
  TEST_INT: 20
  SECRET_VALUE: ${{ secrets.SECRET_VALUE }}

jobs:
  build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-nextjs-app
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './test-nextjs-app/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Upload arfifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: test-nextjs-app/.next/**
          if-no-files-found: error

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: test-nextjs-app/coverage/**

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Output contents
        run: ls

      - name: Deploy
        run: echo 'Deploying... ${{ env.TEST_INT }} and ${{ env.SECRET_VALUE }}'
