name: NextJS Test App CI

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: test-nextjs-app

jobs:
  build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './test-nextjs-app/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload arfifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: test-nextjs-app/.next/**
          if-no-files-found: error

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Output contents
        run: ls -la

      - name: Deploy
        run: echo 'Deploying...'
