name: NextJS Test App CI

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ./test-nextjs-app
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version:
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run linting
        run: npm run lint
